export type RiskDimension = "people" | "process" | "technology" | "governance" | "compliance";

export interface Question {
  code: string;
  text: string;
  why?: string;
  evidenceHint?: string;
  riskDimensions: RiskDimension[];
}

export interface Domain {
  key: string;
  name: string;
  description: string;
  questions: Question[];
}

export const ASSESSMENT_DOMAINS: Domain[] = [
  {
    key: "SITE_CONTEXT",
    name: "Site Profile & Risk Intelligence",
    description: "Grounding security design in the actual risk environment of the facility",
    questions: [
      { code: "SC01", text: "Has a formal site risk assessment been conducted within the last 12 months, covering physical, human, and operational threats specific to this location?", why: "Risk assessments that are not location-specific produce generic controls that miss the actual exposure.", evidenceHint: "Request the risk assessment document. Check the date, assessor credentials, and whether local crime data was referenced.", riskDimensions: ["process", "governance"] },
      { code: "SC02", text: "Are critical asset zones — server rooms, finance floors, executive areas, data centres — formally classified, mapped, and assigned specific protection standards?", why: "Without zone classification, security resources are spread uniformly rather than concentrated where the actual risk lies.", evidenceHint: "Ask for the site security zoning map or access control matrix. Verify it matches the physical layout.", riskDimensions: ["process", "governance"] },
      { code: "SC03", text: "Is there a documented understanding of the local crime pattern — theft, pilferage, tailgating, protests, or neighbourhood incidents — based on liaison with the local police station?", why: "Most Indian corporate sites operate without any structured local threat intelligence, creating blind spots in control design.", evidenceHint: "Ask if they have police liaison contacts, any local crime reports, or neighbourhood watch inputs.", riskDimensions: ["process"] },
      { code: "SC04", text: "Are adjacent risks — construction activity, high-traffic entry roads, proximity to high-value targets, or flood-prone areas — factored into the current security plan?", why: "Environmental adjacency is one of the most under-assessed risk factors in Indian urban offices.", evidenceHint: "Review whether the BCP or risk assessment includes environmental/adjacency risk scenarios.", riskDimensions: ["process"] },
      { code: "SC05", text: "Is the site formally categorised by criticality level (e.g. Tier 1 / Critical, Tier 2 / Significant, Tier 3 / Standard), and does this classification drive resource allocation decisions?", why: "Criticality tiers should be the primary input into guarding strength, technology investment, and response SLAs.", evidenceHint: "Ask how guarding complement and CCTV coverage was determined. If the answer is 'industry norm' rather than risk-based, this is a gap.", riskDimensions: ["governance"] },
      { code: "SC06", text: "Are peak-risk periods — late-night shifts, public holidays, payroll dates, large events, and maintenance windows — specifically planned for in the security roster and protocols?", why: "Most Indian office security incidents occur during predictable windows that are inadequately covered.", evidenceHint: "Review guard duty rosters for the last 3 months. Check if holidays and night shifts are differently staffed.", riskDimensions: ["process"] },
      { code: "SC07", text: "Has the site's Maximum Occupancy, daily average headcount, and shift profile been formally communicated to the security team and used to calibrate the guarding model?", why: "Guarding models calibrated to headcount rather than actual occupancy routinely under- or over-deploy resources.", evidenceHint: "Ask the security manager the site's peak headcount and night minimum. Verify they can answer without looking it up.", riskDimensions: ["process"] },
      { code: "SC08", text: "Are specific seasonal risks — monsoon flooding, festive season elevated theft, election-related civil unrest — addressed in the annual security plan?", why: "Indian operating conditions have strong seasonal risk patterns that generic security plans routinely ignore.", evidenceHint: "Ask whether the security plan is reviewed at the start of monsoon and festive seasons.", riskDimensions: ["process"] },
    ]
  },
  {
    key: "GOVERNANCE",
    name: "Governance, Policy & Security Organisation",
    description: "Security leadership structures, policy frameworks, and accountability in the Indian corporate context",
    questions: [
      { code: "GOV01", text: "Is there a named Security Head or Site Security Manager with documented authority, a clear reporting line, and an updated job description?", why: "Named accountability is the single most reliable predictor of security programme quality.", evidenceHint: "Ask who the security manager reports to and what decisions they can make without escalation.", riskDimensions: ["people", "governance"] },
      { code: "GOV02", text: "Are security policies formally documented, version-controlled, approved by senior leadership, and reviewed at least annually?", why: "Policies that are not reviewed become compliance liabilities and disconnect from evolving operational reality.", evidenceHint: "Request the Security Policy. Check the approval date, version number, and approving authority.", riskDimensions: ["process", "governance", "compliance"] },
      { code: "GOV03", text: "Is security represented in senior management reviews, and are security performance metrics (incidents, compliance, open findings) reported to leadership at least quarterly?", why: "Security programmes without executive visibility are routinely under-resourced and deprioritised during cost pressures.", evidenceHint: "Ask for the last board or leadership deck that included a security update.", riskDimensions: ["process", "governance"] },
      { code: "GOV04", text: "Are security responsibilities clearly defined and communicated for non-security staff — facilities, HR, IT, and business line managers?", why: "In Indian offices, security is frequently treated as the guard's job. This creates systemic blind spots.", evidenceHint: "Ask the Facilities Manager and an HR Business Partner what their security responsibilities are.", riskDimensions: ["people", "process", "governance"] },
      { code: "GOV05", text: "Is there a formal security committee or cross-functional working group that meets at a defined frequency with documented outcomes?", why: "Security committees create structured accountability and ensure security stays on the agenda across functions.", evidenceHint: "Ask for the last three meeting minutes or action trackers from the security committee.", riskDimensions: ["people", "governance"] },
      { code: "GOV06", text: "Is the security budget formally planned on an annual basis, with line-item visibility into guarding costs, technology maintenance, training, and audit/compliance?", why: "Security budgets driven by precedent rather than risk routinely miss critical investment needs.", evidenceHint: "Ask for the current year's security opex and capex plan. If none exists, this is a material gap.", riskDimensions: ["governance"] },
      { code: "GOV07", text: "Are POSH (Prevention of Sexual Harassment) obligations integrated into the security team's awareness and response protocols, particularly for after-hours incidents?", why: "POSH compliance is a legal obligation that intersects directly with physical security — especially for female employees on night shifts.", evidenceHint: "Ask whether the security team is briefed on POSH escalation. Check if the Internal Committee contact is displayed in guard posts.", riskDimensions: ["people", "compliance"] },
      { code: "GOV08", text: "Is there a formal security strategy — not just policy — that defines the programme's direction, target-state maturity, and investment priorities for the next 1–3 years?", why: "Without a strategy, security programmes are reactive. Reactive programmes are always underprepared.", evidenceHint: "Ask what the security programme is trying to achieve in the next 12 months. If the answer is purely operational, the strategy gap is confirmed.", riskDimensions: ["process", "governance"] },
      { code: "GOV09", text: "Are outsourced security vendor performance obligations — response times, training compliance, statutory adherence, incident reporting — formally monitored against contractual SLAs?", why: "Most Indian organisations contract security services but rarely hold vendors accountable to defined performance standards.", evidenceHint: "Ask for the last vendor performance review. Verify it includes statutory compliance, not just headcount compliance.", riskDimensions: ["process", "governance", "compliance"] },
    ]
  },
  {
    key: "PERIMETER",
    name: "Perimeter, Access Control & Physical Infrastructure",
    description: "Boundary integrity, layered physical controls, and access management for Indian urban office environments",
    questions: [
      { code: "PER01", text: "Is the perimeter boundary clearly defined with maintained physical barriers — compound walls, anti-climb fencing, or bollards — appropriate to the site's risk profile?", why: "Undefined or poorly maintained perimeters are the primary enabler of unauthorised entry in Indian urban offices.", evidenceHint: "Walk the perimeter and note gaps, low walls, or accessible rooftops. Ask when the last perimeter integrity inspection was conducted.", riskDimensions: ["technology"] },
      { code: "PER02", text: "Are all pedestrian and vehicle entry/exit points manned, logged, and electronically monitored, including secondary gates, loading docks, and basement entries?", why: "Secondary entry points — loading docks, emergency exits, basement vehicle ramps — are the most commonly exploited access paths in Indian offices.", evidenceHint: "Physically count and map all entry points. Check if any are unmanned during office hours.", riskDimensions: ["process", "technology"] },
      { code: "PER03", text: "Is vehicle access controlled through a vehicle management system — boom barriers, number plate recognition, or vehicle logs — with visitor vehicles separately managed?", why: "Uncontrolled vehicle access is a significant threat vector for theft, tailgating, and physical attacks.", evidenceHint: "Review the vehicle access register for the last 30 days. Check if contractor vehicles are logged separately.", riskDimensions: ["process", "technology"] },
      { code: "PER04", text: "Is a technology-based access control system (card readers, biometrics, or mobile credentials) deployed at all primary entry points, with tailgating detection in place?", why: "Manual access control at high-footfall Indian offices is operationally unsustainable and routinely compromised during peak hours.", evidenceHint: "Test tailgating discipline at the main entry during a peak arrival period. Check if ACS logs are reviewed.", riskDimensions: ["technology"] },
      { code: "PER05", text: "Is there a documented, enforced process for access card lifecycle management — issuance, lost card response, resignation deactivation within 24 hours, and periodic access rights review?", why: "Orphaned access credentials are one of the most common and highest-consequence gaps found in Indian corporate security audits.", evidenceHint: "Ask for the last access rights review report. Check the last date a resigned employee's card was deactivated.", riskDimensions: ["process"] },
      { code: "PER06", text: "Is perimeter lighting functional, well-maintained, and sufficient to support CCTV performance and human deterrence at all hours, including during monsoon and power outage events?", why: "Lighting failures are endemic in Indian offices and routinely go unaddressed due to unclear ownership between security and facilities.", evidenceHint: "Conduct a post-sunset perimeter walk. Note any dark spots. Ask who is responsible for lighting maintenance.", riskDimensions: ["technology"] },
      { code: "PER07", text: "Is there a formal, periodic perimeter integrity inspection programme with documented findings and tracked remediation?", why: "Infrastructure defects accumulate invisibly unless proactively inspected. Annual inspections are insufficient for high-footfall sites.", evidenceHint: "Ask for the last inspection report. Check whether findings have been closed or are open.", riskDimensions: ["process"] },
      { code: "PER08", text: "Are unauthorised entry attempts, perimeter breaches, and security-relevant perimeter events logged, escalated, and reviewed monthly for pattern analysis?", why: "Pattern analysis of entry attempts reveals systematic vulnerabilities that single-event responses miss.", evidenceHint: "Ask for the last month's access exception report. Check if any recurring breach points have been identified.", riskDimensions: ["process", "technology"] },
    ]
  },
  {
    key: "VISITORS",
    name: "Visitor, Vendor & Contractor Management",
    description: "Structured management of all temporary and third-party access in the Indian corporate office environment",
    questions: [
      { code: "VIS01", text: "Is there a digital visitor management system that captures government-issued photo ID, host employee name, purpose, and time-in/time-out for every visitor — including delivery personnel?", why: "Paper registers are unreliable, unanalysable, and frequently incomplete. Digital capture is the baseline for any credible Indian corporate office.", evidenceHint: "Ask to see the last 30-day visitor log. Check if all fields are populated. Review how delivery visits are handled.", riskDimensions: ["process", "technology"] },
      { code: "VIS02", text: "Are all visitors — including senior guests, auditors, and maintenance personnel — issued a time-limited physical pass and escorted to their destination by the host employee?", why: "Unescorted visitors in Indian offices routinely access areas beyond their permitted zones, particularly when the visitor is senior or familiar.", evidenceHint: "Observe the visitor flow at reception during a typical morning. Check whether escort discipline holds for VIP guests.", riskDimensions: ["people", "process"] },
      { code: "VIS03", text: "Are AMC vendors and repeat maintenance contractors (housekeeping, pantry, IT support) issued controlled, time-bound credentials and are they subject to the same access discipline as first-time visitors?", why: "Repeat vendors are the most common source of insider-enabled theft in Indian offices because familiarity erodes enforcement.", evidenceHint: "Ask how AMC vendors are managed. Check if they have standing, unreviewed access or time-bound credentials.", riskDimensions: ["process"] },
      { code: "VIS04", text: "Is background verification (police verification or equivalent) required for all contractors who have regular, unsupervised access to the site — including pantry staff, housekeeping, and AMC engineers?", why: "Indian labour contracting structures mean that high-access roles frequently bypass the background checks applied to direct employees.", evidenceHint: "Ask for BGV records for the housekeeping supervisor and the IT AMC engineer. Verify the verification was done by the contractor.", riskDimensions: ["people", "process"] },
      { code: "VIS05", text: "Are visitor and contractor access logs reviewed on at least a weekly basis for anomalies — unusual times, multiple entries, unreturned passes, or access to restricted areas?", why: "Unreviewed logs provide a false sense of control. Anomalies detected late are often detected post-incident.", evidenceHint: "Ask who reviews the visitor log, at what frequency, and for an example of an anomaly that was flagged.", riskDimensions: ["process"] },
      { code: "VIS06", text: "Is there a designated, supervised lobby or visitor reception area that physically prevents visitors from entering the office floor without cleared host escort?", why: "Open-plan lobbies that double as office access points are one of the most common physical security design failures in Indian IT/ITES offices.", evidenceHint: "Map the visitor path from main entrance to the first desk. Identify points at which a visitor could deviate undetected.", riskDimensions: ["process"] },
      { code: "VIS07", text: "Are there documented, enforced protocols for managing the access of ex-employees who return as contractors, auditors, or visitors — including a notification to security?", why: "Ex-employees returning in another capacity are a high-risk category that most Indian organisations do not specifically manage.", evidenceHint: "Ask if the security team is notified when an ex-employee is expected on-site in any capacity.", riskDimensions: ["process"] },
      { code: "VIS08", text: "Is the movement of high-value equipment — laptops, servers, projectors, or cash — into and out of the facility logged, authorised in advance, and physically verified by security?", why: "Asset pilferage through casual porterage is common in Indian offices. A gate pass system is the baseline control.", evidenceHint: "Ask to see the asset movement register for the last month. Check whether IT is issuing gate passes.", riskDimensions: ["people", "process"] },
    ]
  },
  {
    key: "GUARDS",
    name: "Guarding Operations & Statutory Compliance",
    description: "Man-guarding operations, statutory compliance (PSARA, Labour Codes, PF/ESI, wages), and supervisory discipline",
    questions: [
      { code: "GRD01", text: "Is a valid PSARA licence in place for the specific state(s) of operation, and is it current, displayed at the site, and held by the actual agency supplying guards?", why: "Operating without a valid PSARA licence exposes the principal employer to criminal and civil liability under the PSARA Act 2005.", evidenceHint: "Request and inspect the PSARA licence. Verify the issuing state matches the site state, and the validity date is current.", riskDimensions: ["compliance"] },
      { code: "GRD02", text: "Is 100% police verification completed for all deployed guards and supervisors — not just during onboarding but revalidated for staff posted for more than 2 years?", why: "Police verification quality across Indian agencies varies enormously. Periodic revalidation catches guards whose circumstances have changed.", evidenceHint: "Pull 5 random guard files and verify police verification documents exist, are original, and are not older than 3 years.", riskDimensions: ["people", "compliance"] },
      { code: "GRD03", text: "Are PF and ESI contributions being deposited for 100% of deployed personnel on time, and are monthly ECR (Electronic Challan cum Return) records accessible for principal employer review?", why: "Under the Code on Social Security 2020, principal employers carry joint liability for contractor PF/ESI defaults. This is the single highest-value compliance risk in Indian guarding.", evidenceHint: "Ask for the last 3 months' PF ECR challans. Cross-check the employee count against the deployed headcount.", riskDimensions: ["compliance"] },
      { code: "GRD04", text: "Are guards and supervisors paid at or above the applicable state minimum wage under the Code on Wages 2019, and is this verified by the principal employer rather than self-certified by the vendor?", why: "Minimum wage violations by guarding agencies create direct vicarious liability for the principal employer under Indian labour law.", evidenceHint: "Obtain the current state minimum wage notification and compare it against the wage slips of 3 randomly selected guards.", riskDimensions: ["compliance"] },
      { code: "GRD05", text: "Are wage slips issued on time each month, bonus and gratuity entitlements correctly calculated and paid, and overtime tracked within the statutory 8-hour duty limit?", why: "Over-hours deployment without documented overtime is endemic in Indian guarding and creates both compliance and performance risk.", evidenceHint: "Review the last month's duty roster for any guard posted for more than 8 hours per shift. Ask when gratuity was last reviewed.", riskDimensions: ["process", "compliance"] },
      { code: "GRD06", text: "Is there a formal, risk-calibrated deployment plan — defining post-wise manning requirements, duties, patrol routes, and escalation authority — that is reviewed when the site risk profile changes?", why: "Most Indian guarding deployments are driven by convention rather than risk. This produces miscalibrated manning at every site.", evidenceHint: "Ask for the site's manning plan and post orders. Check whether they reference specific risks or are generic.", riskDimensions: ["people", "process"] },
      { code: "GRD07", text: "Is site-specific induction training — covering the facility layout, emergency procedures, PSARA requirements, and post-specific duties — completed before a guard is deployed?", why: "Guards deployed without site-specific induction routinely make preventable errors in their first weeks, which is when most guarding failures occur.", evidenceHint: "Ask the guard on duty to describe the emergency evacuation procedure. The quality of the answer reveals training effectiveness.", riskDimensions: ["people", "process"] },
      { code: "GRD08", text: "Is there a 24/7 Control Room with continuous monitoring capability, documented shift-handover protocols, and an updated site communication directory accessible to the on-duty team?", why: "Without a functional control room, the response to any security event depends entirely on the individual guard's judgement and communication ability.", evidenceHint: "Visit the control room during a shift handover. Check whether the handover is documented and whether the communication directory is current.", riskDimensions: ["process"] },
      { code: "GRD09", text: "Does the principal employer conduct at least quarterly independent audits of the guarding vendor's statutory compliance — not relying solely on vendor self-declarations?", why: "Guarding vendors routinely self-certify compliance. Principal employer verification is a legal and operational imperative.", evidenceHint: "Ask for the last audit report conducted by or on behalf of the principal employer. Verify it was not produced by the vendor.", riskDimensions: ["governance", "compliance"] },
      { code: "GRD10", text: "Are guard retention, absenteeism, and attrition rates monitored, and is persistent absenteeism or high attrition treated as a performance signal requiring vendor accountability?", why: "High guard attrition is both a quality signal and a statutory risk indicator. Unmonitored attrition produces perpetually undertrained deployments.", evidenceHint: "Ask the vendor for the last 3 months' attrition data for this site. If they cannot provide it, that itself is the finding.", riskDimensions: ["people", "governance"] },
    ]
  },
  {
    key: "ELECTRONIC",
    name: "Electronic Security Systems (CCTV, ACS & Integration)",
    description: "CCTV, access control, intrusion detection, and technology integration for Indian corporate offices",
    questions: [
      { code: "ELC01", text: "Does CCTV coverage include all entry/exit points, server rooms, cash handling areas, executive floors, parking, and loading docks — with no blind spots in critical zones?", why: "CCTV coverage maps in Indian offices routinely lag behind the actual facility layout due to expansions and refurbishments.", evidenceHint: "Request the CCTV layout map and physically verify camera positions against critical zones. Ask when the last coverage audit was done.", riskDimensions: ["technology"] },
      { code: "ELC02", text: "Are CCTV recordings retained for a minimum of 30 days, automatically backed up, and stored in a manner that prevents tampering or accidental deletion?", why: "Indian regulatory and investigation requirements increasingly mandate 30-day retention. Shorter retention or deletable recordings compromise post-incident utility.", evidenceHint: "Check the DVR/NVR retention settings. Ask how recordings are backed up and who has deletion rights.", riskDimensions: ["process", "technology"] },
      { code: "ELC03", text: "Is CCTV actively monitored in real-time — not just recorded — during all operating hours, with a defined response protocol when an anomaly is detected on camera?", why: "Recording-only CCTV provides forensic value but zero deterrence or prevention value. Real-time monitoring is what converts cameras into an active control.", evidenceHint: "Ask the control room operator to demonstrate how they monitor live feeds. Check how many cameras one operator is expected to watch simultaneously.", riskDimensions: ["process", "technology"] },
      { code: "ELC04", text: "Is there a preventive maintenance schedule for all electronic security systems — CCTV, ACS, IDS, intercom — with documented maintenance history and vendor SLAs?", why: "Electronic security systems in Indian offices routinely degrade unnoticed due to absent maintenance programmes. A broken camera provides negative assurance.", evidenceHint: "Ask for the AMC contract and last maintenance report. Check the last time each camera was physically cleaned and focused.", riskDimensions: ["process"] },
      { code: "ELC05", text: "Are access control logs reviewed on at least a weekly basis for after-hours access, failed attempts, duplicate badge use, and access to restricted areas?", why: "Access control logs are the richest source of insider threat signals in any corporate facility. Unreviewed logs are a wasted investment.", evidenceHint: "Ask who reviews access logs and at what frequency. Request an example of an anomaly that was detected through log review.", riskDimensions: ["process", "technology"] },
      { code: "ELC06", text: "Is there an intrusion detection system (IDS) or perimeter alarm covering the building exterior and critical internal zones, with alarms integrated into the control room and tested monthly?", why: "After-hours intrusion detection is particularly critical in Indian facilities where night-time guarding is often at minimum strength.", evidenceHint: "Ask when the IDS was last tested. Check if there is a documented alarm response procedure.", riskDimensions: ["technology"] },
      { code: "ELC07", text: "Are the cybersecurity aspects of electronic security systems — CCTV network segregation, default password changes, firmware updates, and remote access controls — managed by IT in coordination with Security?", why: "IP-based CCTV and access control systems on corporate networks are a growing attack vector and are almost universally misconfigured in Indian corporate offices.", evidenceHint: "Ask whether security system devices are on a segregated VLAN. Ask when firmware was last updated. Ask who holds remote access credentials.", riskDimensions: ["technology"] },
      { code: "ELC08", text: "Is there a documented technology refresh roadmap for electronic security systems, with end-of-life equipment identified and replacement budgeted?", why: "Indian corporate offices routinely run CCTV and ACS systems well beyond their effective life, creating both reliability and cybersecurity risks.", evidenceHint: "Ask how old the current CCTV system is and when it is scheduled for replacement.", riskDimensions: ["governance", "technology"] },
    ]
  },
  {
    key: "INCIDENTS",
    name: "Incident Management, Response & Security Operations",
    description: "Structured incident handling, SOC operations, and response effectiveness in Indian corporate settings",
    questions: [
      { code: "INC01", text: "Is there a documented Incident Response Plan with a clearly defined severity classification matrix, escalation path, and named decision-makers at each level?", why: "Undocumented incident response in Indian offices produces inconsistent, person-dependent responses that amplify incident impact.", evidenceHint: "Request the IRP document. Check if it covers the full severity spectrum — from minor theft to bomb threat to fire — and if escalation contacts are current.", riskDimensions: ["people", "process", "governance"] },
      { code: "INC02", text: "Are all security incidents — including minor events, near-misses, and security observations — logged in a structured register with date, time, location, type, response, and closure status?", why: "Pattern analysis of minor incidents is the most reliable predictor of serious events. Sites that only log major incidents consistently miss emerging threat patterns.", evidenceHint: "Ask for the incident register for the last 6 months. Check if near-misses and observations are included, not just confirmed incidents.", riskDimensions: ["process"] },
      { code: "INC03", text: "Are response time standards defined for each incident severity level — and is actual response time measured against these standards on a monthly basis?", why: "Unmeasured response is unmanaged response. Indian guarding contracts routinely specify response SLAs that are never actually tracked.", evidenceHint: "Ask for last month's response time performance data. If it does not exist, the SLA exists only on paper.", riskDimensions: ["process"] },
      { code: "INC04", text: "Is root cause analysis (RCA) conducted for all incidents above a defined severity level, with corrective actions tracked to closure and communicated to stakeholders?", why: "Incident recurrence is the defining indicator of a reactive security programme. RCA breaks the recurrence cycle.", evidenceHint: "Ask for the last three RCA reports. Check whether the corrective actions were closed or remain open.", riskDimensions: ["process"] },
      { code: "INC05", text: "Is there a tested, coordinated protocol for escalating security incidents to senior leadership, HR, Legal, and external authorities (police, ambulance) — with contact details verified quarterly?", why: "Escalation failures during serious incidents in Indian offices are frequently traced to outdated contact lists and unclear escalation triggers.", evidenceHint: "Ask the security manager to walk through the escalation for a hypothetical serious incident. Check when contact lists were last verified.", riskDimensions: ["process"] },
      { code: "INC06", text: "Are security incidents and near-misses reviewed in a monthly security meeting that includes security, facilities, and HR — with action items tracked across functions?", why: "Security reviews that happen within the security function alone miss the cross-functional contributing factors that produce incidents.", evidenceHint: "Ask for the last 3 months' security review meeting minutes.", riskDimensions: ["process", "governance"] },
      { code: "INC07", text: "Is there a documented, practised protocol for liaising with local police — including named SHO contacts, FIR filing procedures, and evidence preservation steps?", why: "Indian organisations frequently delay or mismanage police engagement during incidents, compromising both investigation and legal recourse.", evidenceHint: "Ask the security manager for the local police station name, SHO name, and when they last spoke to the station.", riskDimensions: ["process"] },
      { code: "INC08", text: "Is the security team trained and equipped to handle medical emergencies — with a qualified first-aider on every shift, an accessible first aid kit, and the nearest hospital route known and communicated?", why: "Medical emergencies are the most frequent serious incidents in Indian corporate offices. Poor first response is a significant reputational and legal risk.", evidenceHint: "Ask which guard on the current shift has first-aid certification. Ask for the first aid kit and check its contents and expiry dates.", riskDimensions: ["people", "process"] },
    ]
  },
  {
    key: "CULTURE",
    name: "Employee Security Culture & Awareness",
    description: "Embedding security consciousness as an organisational behaviour, not a training tick-box",
    questions: [
      { code: "CUL01", text: "Is security awareness training — covering tailgating, phishing-physical interaction, visitor management, and incident reporting — delivered as part of every new employee induction?", why: "New employees are disproportionately involved in security incidents in their first 90 days due to unfamiliarity with site protocols.", evidenceHint: "Ask HR for the new employee induction agenda. Check whether security content is included or is a separate, optional module.", riskDimensions: ["people", "process"] },
      { code: "CUL02", text: "Is security awareness refreshed at least annually through formats that go beyond email circulars — desk drops, town halls, simulated phishing-physical exercises, or video communications?", why: "Annual email circulars do not change behaviour. Format diversity is the primary driver of awareness programme effectiveness.", evidenceHint: "Ask what security awareness activities were conducted in the last 12 months beyond email communications.", riskDimensions: ["people", "process"] },
      { code: "CUL03", text: "Is there a simple, trusted, and widely known mechanism for employees to report security concerns — anonymous or named — without fear of professional consequence?", why: "Most Indian offices have formal reporting channels that employees do not trust or are unaware of, producing severely under-reported threat intelligence.", evidenceHint: "Ask 3 random non-security employees how they would report a security concern. The quality of their answers is the data.", riskDimensions: ["people", "governance"] },
      { code: "CUL04", text: "Is tailgating actively managed — through turnstile design, guard alertness, and a visible cultural norm that employees are expected to challenge unauthorised access — rather than just policy?", why: "Tailgating discipline in Indian offices consistently breaks down because social norms override policy when they are not reinforced with physical and behavioural controls.", evidenceHint: "Observe a peak-time entry period. Count how many tailgating events occur. Ask guards what they do when they observe it.", riskDimensions: ["people"] },
      { code: "CUL05", text: "Are clear desk, screen lock, and clean desk policies enforced through periodic, unannounced compliance sweeps — not just communicated through policy?", why: "Policies without enforcement audits are universally non-compliant in Indian office environments after the first few weeks.", evidenceHint: "Ask when the last clean desk audit was conducted and what the findings were.", riskDimensions: ["people", "process"] },
      { code: "CUL06", text: "Do business leaders and senior managers visibly model security behaviours — wearing badges, following access procedures, and participating in drills — rather than seeking or receiving exemptions?", why: "Leadership exemptions from security protocols are the fastest way to undermine a security culture in Indian organisations. Staff observe and replicate leadership behaviour.", evidenceHint: "Ask the security manager whether senior leadership wears access badges. Ask whether VIPs are escorted or exempted.", riskDimensions: ["people", "governance"] },
      { code: "CUL07", text: "Are security champions or floor security coordinators identified within business units, with a defined role in relaying security communications and being a first point of contact for concerns?", why: "Security champions bridge the gap between the security function and the business in a way that centralised communication cannot.", evidenceHint: "Ask who the security champion is for a specific business floor. If neither security nor a business employee can answer, the role is not functioning.", riskDimensions: ["people", "governance"] },
      { code: "CUL08", text: "Is employee security behaviour measured — through compliance audits, drill participation rates, and reporting volumes — and are trends shared with leadership to drive accountability?", why: "What is not measured is not managed. Security culture measurement is the mechanism that sustains programmes beyond initial implementation.", evidenceHint: "Ask for the last culture or compliance measurement report. If one does not exist, the programme is not being evaluated.", riskDimensions: ["people", "process"] },
    ]
  },
  {
    key: "BCP",
    name: "Business Continuity, Emergency Response & Crisis Management",
    description: "Tested emergency preparedness and crisis management capability for Indian office environments",
    questions: [
      { code: "BCP01", text: "Is there a documented Business Continuity Plan (BCP) that covers the specific recovery requirements of the business units operating from this site — not a generic template?", why: "Generic BCP templates that do not reflect the site's actual business functions provide false assurance and fail during real disruptions.", evidenceHint: "Request the BCP. Check whether it names the specific business functions at this site and their recovery time objectives.", riskDimensions: ["process", "governance", "compliance"] },
      { code: "BCP02", text: "Are fire safety systems — sprinklers, fire doors, extinguishers, smoke detectors, and hydrants — fully functional, inspected within the last 6 months, and compliant with NBC and local fire NOC requirements?", why: "Fire NOC compliance is a legal obligation in India, and fire system failures during incidents carry criminal liability for the building occupant.", evidenceHint: "Ask for the last fire system inspection report. Check whether the fire NOC is current. Physically test one extinguisher pressure gauge.", riskDimensions: ["technology", "compliance"] },
      { code: "BCP03", text: "Are emergency evacuation drills conducted at least bi-annually, including a minimum of one unannounced drill, with full participation tracked and evacuation time recorded?", why: "Announced-only drills produce practised performance in rehearsed conditions. Unannounced drills reveal actual organisational readiness.", evidenceHint: "Ask for the last two drill records. Check if one was unannounced. Ask what the recorded evacuation time was.", riskDimensions: ["process", "compliance"] },
      { code: "BCP04", text: "Is there a Crisis Management Team (CMT) with defined roles, current contact details, a tested communication tree, and a designated crisis command location?", why: "Crisis management teams without practised communication trees and a known command location lose critical minutes during actual crises.", evidenceHint: "Ask who is on the CMT. Call or check the most recent emergency contact directory to verify its currency.", riskDimensions: ["people", "governance"] },
      { code: "BCP05", text: "Is there a documented, practised protocol for communicating with employees, their families, and external stakeholders during a crisis — including for scenarios involving casualties?", why: "Employee family communication is the most consistently neglected element of Indian corporate crisis management and the highest source of reputational damage during incidents.", evidenceHint: "Ask whether the emergency communication protocol covers what to say to an employee's family if the employee is injured.", riskDimensions: ["process"] },
      { code: "BCP06", text: "Are relationships with local emergency services — fire brigade, police, nearest hospital — formalised with current contact details, and is the site accessible to emergency vehicles at all times?", why: "Emergency service response in Indian metro areas is variable. Pre-established relationships materially improve response speed.", evidenceHint: "Ask when the security team last spoke to the local fire station. Ask if the fire brigade has visited the site.", riskDimensions: ["process"] },
      { code: "BCP07", text: "Are critical business function recovery priorities formally documented, with IT recovery time objectives (RTO) and recovery point objectives (RPO) aligned with security and facilities?", why: "Business continuity plans that are not aligned with IT recovery objectives produce uncoordinated responses during technology-related disruptions.", evidenceHint: "Ask the security head for the RTO of the most business-critical function on site. If they cannot answer, BCP-security alignment is the gap.", riskDimensions: ["process", "governance"] },
      { code: "BCP08", text: "Has the BCP been formally tested — through tabletop exercises or simulated disruptions — within the last 12 months, with lessons identified and documented?", why: "Untested BCPs fail in two predictable ways: communication trees are outdated, and decision-makers are unfamiliar with their roles.", evidenceHint: "Ask for the last BCP test report or tabletop exercise summary.", riskDimensions: ["process", "governance"] },
    ]
  },
  {
    key: "COMPLIANCE",
    name: "Compliance, Audit Readiness & Third-Party Risk",
    description: "Regulatory compliance, audit preparedness, and third-party risk management in the Indian legal framework",
    questions: [
      { code: "COM01", text: "Are security policies and controls formally mapped to applicable Indian regulatory requirements — including DPDP Act 2023, IT Act 2000, labour laws, and client contractual security obligations?", why: "The DPDP Act 2023 introduces significant physical security obligations for data fiduciaries. Most Indian offices have not yet mapped physical controls to this new framework.", evidenceHint: "Ask whether the security team has reviewed the DPDP Act requirements. Ask if client security SLAs are mapped to specific controls.", riskDimensions: ["process", "governance", "compliance"] },
      { code: "COM02", text: "Are formal internal security audits conducted at least annually — with a structured scope, independent assessors, written findings, and a tracked CAPA register?", why: "Security programmes without independent audit cycles accumulate control degradation that is invisible to the security team itself.", evidenceHint: "Request the last internal audit report. Check whether the auditor was independent of the security function.", riskDimensions: ["process", "compliance"] },
      { code: "COM03", text: "Is there a live CAPA (Corrective and Preventive Action) tracker for all security audit findings — with owner names, due dates, and current status visible to security leadership?", why: "Audit findings without a managed CAPA process routinely recur. Open CAPAs are the most common finding in follow-up audits.", evidenceHint: "Ask for the CAPA register. Check how many findings from the last audit are still open and by how many days they are overdue.", riskDimensions: ["process"] },
      { code: "COM04", text: "Are all security-related records — incident logs, guard records, access logs, visitor registers, training records — maintained in a retrievable format for a minimum of 3 years?", why: "Indian labour and security regulations routinely require documentation going back 2–5 years. Organisations that do not maintain records cannot demonstrate compliance.", evidenceHint: "Ask for an incident log from 18 months ago. If it cannot be produced, the retention programme is inadequate.", riskDimensions: ["process", "compliance"] },
      { code: "COM05", text: "Is a third-party security risk assessment conducted before engaging any vendor with physical access to the site — and is this revisited annually for long-term vendors?", why: "Third-party supply chains are the most rapidly growing physical security risk vector in Indian corporate environments.", evidenceHint: "Ask how a new vendor is security-assessed before they are allowed on-site. Check if any standing vendors have been reassessed in the last 12 months.", riskDimensions: ["process", "governance"] },
      { code: "COM06", text: "Are data protection measures physically integrated — secure printing, clean desk, no photography zones, screen privacy filters in public areas, and data destruction protocols?", why: "The DPDP Act 2023 extends data protection obligations into physical environments. Physical data protection controls are increasingly subject to regulatory scrutiny.", evidenceHint: "Visit the printer area. Check if uncollected printouts are present. Ask whether a secure destruction service is contracted.", riskDimensions: ["technology", "compliance"] },
      { code: "COM07", text: "Are security vendor contracts structured with explicit SLAs, statutory compliance obligations, audit rights for the principal employer, and termination provisions linked to non-compliance?", why: "Indian security vendor contracts frequently lack audit rights and compliance linkage, making it impossible to enforce standards or exit non-performing vendors.", evidenceHint: "Request the current security vendor contract. Check for audit rights, SLA definitions, and compliance termination clauses.", riskDimensions: ["process", "governance"] },
      { code: "COM08", text: "Are the site's insurance coverages — property, liability, fidelity, and key person — reviewed annually against the current asset value and risk profile, with security as an input to the review?", why: "Insurance gaps discovered post-incident are a major source of unrecovered loss in Indian corporate security contexts.", evidenceHint: "Ask when insurance coverage was last reviewed and whether the security team was consulted. Ask for the current sum insured for movable assets.", riskDimensions: ["governance", "compliance"] },
    ]
  },
];

export const SCALE_LABELS: { [key: number]: string } = { 1: "Ad-hoc", 2: "Developing", 3: "Defined", 4: "Managed", 5: "Resilient" };

export const getRatingLabel = (rating: number): string => {
  return SCALE_LABELS[rating] || "";
};

export const getMaturityLevel = (rawScore: number): number => {
  if (rawScore <= 1.8) return 1;
  if (rawScore <= 2.6) return 2;
  if (rawScore <= 3.4) return 3;
  if (rawScore <= 4.2) return 4;
  return 5;
};

export const getMaturityLabel = (level: number): string => {
  return SCALE_LABELS[level] || "";
};

export const getRiskPosture = (score: number): string => {
  if (score <= 40) return "High Risk";
  if (score <= 60) return "Developing";
  if (score <= 75) return "Maturing";
  return "Resilient";
};

export const DOMAIN_WEIGHTS: Record<string, number> = {
  SITE_CONTEXT: 0.08,
  GOVERNANCE: 0.10,
  PERIMETER: 0.12,
  VISITORS: 0.10,
  GUARDS: 0.15,
  ELECTRONIC: 0.12,
  INCIDENTS: 0.12,
  CULTURE: 0.08,
  BCP: 0.08,
  COMPLIANCE: 0.15,
};

export const getScoreColor = (score: number): string => {
  if (score <= 50) return "score-low";
  if (score <= 75) return "score-medium";
  return "score-high";
};
