import { Card, CardContent } from "@/components/ui/card";
import { ScrollText, ShieldCheck, FileCheck2, Clock } from "lucide-react";

interface AuditTrailProps {
  createdAt?: string | null;
  submittedAt?: string | null;
  reportReadyAt?: string | null;
  reviewedByName?: string | null;
  reviewedByRole?: string | null;
  /** When set, renders the Validated stamp instead of pending-review copy. */
  validatedAt?: string | null;
  /** "quick" (auto-generated by SIP™ Intelligence Engine) or "validated" (Advisory Team). */
  reportTier?: "quick" | "validated";
  className?: string;
}

const fmt = (iso?: string | null) => {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return "—";
  }
};

/**
 * Read-only audit & evidence trail ribbon for intelligence reports.
 * Reinforces the "audit-tracked" trust posture using existing assessment metadata.
 */
const AuditTrail = ({
  createdAt,
  submittedAt,
  reportReadyAt,
  reviewedByName,
  reviewedByRole,
  validatedAt,
  reportTier = "quick",
  className = "",
}: AuditTrailProps) => {
  const isValidated = reportTier === "validated" && !!validatedAt;
  const validatedLabel = isValidated
    ? "Specialist Validated"
    : reportTier === "validated"
      ? "Validation in progress"
      : "Auto-generated";
  const validatedSub = isValidated
    ? "Reviewed and validated by the SIP™ Advisory Team"
    : reportTier === "validated"
      ? "SIP™ Advisory Team review pending"
      : "SIP™ Intelligence Engine — instant diagnostic";
  return (
    <Card className={`border-border/60 bg-muted/30 ${className}`}>
      <CardContent className="p-4">
        <div className="flex items-center gap-2 mb-3">
          <ScrollText className="h-3.5 w-3.5 text-secondary" />
          <p className="text-[11px] uppercase tracking-[0.2em] text-muted-foreground font-semibold">
            Audit & Evidence Trail
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1 inline-flex items-center gap-1">
              <Clock className="h-3 w-3" /> Initiated
            </p>
            <p className="font-mono text-foreground">{fmt(createdAt)}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1 inline-flex items-center gap-1">
              <FileCheck2 className="h-3 w-3" /> Submitted
            </p>
            <p className="font-mono text-foreground">{fmt(submittedAt)}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1 inline-flex items-center gap-1">
              <ShieldCheck className="h-3 w-3 text-accent" /> Report Ready
            </p>
            <p className="font-mono text-foreground">{fmt(reportReadyAt)}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wider text-muted-foreground mb-1">{isValidated ? "Validated By" : "Status"}</p>
            <p className="font-medium text-foreground truncate">{validatedLabel}</p>
            <p className="text-[10px] text-muted-foreground truncate">{validatedSub}</p>
            {isValidated && validatedAt && (
              <p className="text-[10px] font-mono text-muted-foreground mt-0.5">{fmt(validatedAt)}</p>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default AuditTrail;
