import { useState } from "react";
import { ShieldAlert, ChevronRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface Props {
  tier: "quick" | "validated";
  /** "sticky" (default) keeps it pinned to the report column; "inline" renders as a normal block; "print" inlines the full clause for PDF/print. */
  variant?: "sticky" | "inline" | "print";
  className?: string;
}

const WARM_LINE: Record<"quick" | "validated", string> = {
  quick:
    "Built from what you told us — your judgement still runs the site.",
  validated:
    "Specialist-reviewed intelligence, not a guarantee. PSARA, DPDP and ISO references show alignment direction, not certification.",
};

const FormalClause = ({ tier }: { tier: "quick" | "validated" }) => (
  <div className="space-y-3 text-sm leading-relaxed text-muted-foreground font-body">
    <Section n="1" title="What this is.">
      An intelligence product issued by SIP™ to help security leaders prioritise.
      It is <em>not</em> an audit opinion, certification, or assurance engagement.
    </Section>
    <Section n="2" title="Not a compliance certificate.">
      Nothing in this report certifies conformance with PSARA 2005, the Digital
      Personal Data Protection Act 2023, ISO 18788, ISO 22301, the Labour Codes,
      or any other statute, standard, or contract. Alignment notes indicate
      <em> direction</em>, not attestation.
    </Section>
    <Section n="3" title="Based on self-reported data.">
      Findings are generated from ratings, evidence and context supplied by the
      user. Accuracy depends on the inputs. SIP™ does not independently verify
      site conditions, documents, or controls.
    </Section>
    <Section n="4" title="No outcome guarantee.">
      Implementing recommendations does not guarantee prevention of incidents,
      breaches, losses, injuries, regulatory action, or any other outcome.
      Security risk cannot be eliminated.
    </Section>
    <Section n="5" title="Not legal, financial, insurance or engineering advice.">
      Consult qualified counsel, insurers, chartered engineers or licensed
      agencies before acting.
    </Section>
    <Section n="6" title="AI-assisted content.">
      Portions are generated by AI models and may contain errors.
      {tier === "validated"
        ? " Specialist commentary reflects the reviewer's professional opinion at the time of review and may evolve as conditions change."
        : " The Validated Intelligence Report (released within 24 hours) adds specialist commentary and peer context."}
    </Section>
    <Section n="7" title="Confidentiality & sharing.">
      Shareable links are intended for internal leadership use. Recipients are
      bound by the same scope and limits. Do not publish externally without
      written consent.
    </Section>
    <Section n="8" title="Limitation of liability.">
      To the maximum extent permitted by law, SIP™, its affiliates, contributors
      and reviewers accept no liability for any direct, indirect, incidental or
      consequential loss arising from reliance on this report.
    </Section>
    <Section n="9" title="Governing terms.">
      Use of this report is governed by SIP™'s Terms of Service and Privacy
      Policy and the laws of India. Disputes are subject to the exclusive
      jurisdiction of competent courts in India.
    </Section>
    <p className="text-[11px] uppercase tracking-wider pt-2 border-t border-border/40">
      Security Selfie™, Security Intelligence Platform™ and SIP™ are trademarks
      of SIP™.
    </p>
  </div>
);

const Section = ({ n, title, children }: { n: string; title: string; children: React.ReactNode }) => (
  <p>
    <span className="font-mono text-xs text-secondary mr-1.5">{n}.</span>
    <span className="font-semibold text-foreground">{title}</span>{" "}
    <span>{children}</span>
  </p>
);

const ReportDisclaimerRibbon = ({ tier, variant = "sticky", className = "" }: Props) => {
  const [open, setOpen] = useState(false);
  const tierLabel = tier === "validated" ? "Validated" : "Quick";

  // Print variant: full clause visible, no dialog, page-break before to keep it together.
  if (variant === "print") {
    return (
      <section
        className={`mt-8 pt-6 border-t border-border/60 ${className}`}
        style={{ pageBreakBefore: "always" }}
        aria-label="About this report — scope, limits and governing terms"
      >
        <div className="flex items-start gap-3 mb-4">
          <ShieldAlert className="h-5 w-5 text-secondary mt-0.5 shrink-0" />
          <div>
            <h2 className="font-heading text-lg font-semibold text-foreground">
              About this report — scope, limits and governing terms
            </h2>
            <p className="text-sm text-muted-foreground mt-1 italic">{WARM_LINE[tier]}</p>
            <Badge variant="outline" className="mt-2 text-[10px] uppercase tracking-wider">
              {tierLabel} Intelligence Report
            </Badge>
          </div>
        </div>
        <FormalClause tier={tier} />
      </section>
    );
  }

  const wrapperBase =
    "border-t border-border/40 bg-card/85 backdrop-blur supports-[backdrop-filter]:bg-card/70 print:hidden";
  const wrapperPosition =
    variant === "sticky" ? "sticky bottom-0 z-30 -mx-4 md:-mx-6 px-4 md:px-6" : "";

  return (
    <>
      <div className={`${wrapperBase} ${wrapperPosition} ${className}`} role="contentinfo" aria-label="Report disclaimer">
        <div className="py-2.5 flex items-center gap-3 flex-wrap">
          <ShieldAlert className="h-4 w-4 text-secondary shrink-0" aria-hidden />
          <Badge variant="outline" className="text-[10px] uppercase tracking-wider shrink-0">
            {tierLabel}
          </Badge>
          <p className="font-heading text-xs md:text-sm text-muted-foreground flex-1 min-w-[200px] leading-snug">
            {WARM_LINE[tier]}
          </p>
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button size="sm" variant="ghost" className="h-8 text-xs gap-1 shrink-0">
                Read the fine print
                <ChevronRight className="h-3.5 w-3.5" />
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2 font-heading">
                  <ShieldAlert className="h-5 w-5 text-secondary" />
                  About this report — scope, limits and governing terms
                </DialogTitle>
              </DialogHeader>
              <div className="mt-2">
                <p className="text-sm italic text-muted-foreground mb-4">{WARM_LINE[tier]}</p>
                <FormalClause tier={tier} />
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </div>
    </>
  );
};

export default ReportDisclaimerRibbon;
